
trigger:
- main
 
pool:
  uipath
 
steps:

- task: UiPathPack@4
  inputs:
    versionType: 'AutoVersion'
    projectJsonPath: '$(Build.SourcesDirectory)/VM_PL01_CreateNewProductLineItem/project.json'
    orchestratorConnection: 'Uipath'
    outputPath: '$(Build.ArtifactStagingDirectory)/Output/'
- task: UiPathDeploy@4
  inputs:
    orchestratorConnection: 'Uipath'
    packagesPath: '$(Build.ArtifactStagingDirectory)/Output/'
    folderName: 'Variant_Matrix_Automations'

- script: |
   del /S "$(Build.ArtifactStagingDirectory)\Output\*.nupkg"
  displayName: 'Delete output folder'

- task: UiPathPack@4
  inputs:
    versionType: 'AutoVersion'
    projectJsonPath: '$(Build.SourcesDirectory)/VM_PL_01_RemovalOfPartsinVM/project.json'
    orchestratorConnection: 'Uipath'
    outputPath: '$(Build.ArtifactStagingDirectory)/Output/'
- task: UiPathDeploy@4
  inputs:
    orchestratorConnection: 'Uipath'
    packagesPath: '$(Build.ArtifactStagingDirectory)/Output/'
    folderName: 'Variant_Matrix_Automations'

- script: |
   del /S "$(Build.ArtifactStagingDirectory)\Output\*.nupkg"
  displayName: 'Delete output folder'

- task: UiPathPack@4
  inputs:
    versionType: 'AutoVersion'
    projectJsonPath: '$(Build.SourcesDirectory)/VM_PL_01_RemovalOfTwoPartsInVM/project.json'
    orchestratorConnection: 'Uipath'
    outputPath: '$(Build.ArtifactStagingDirectory)/Output/'
- task: UiPathDeploy@4
  inputs:
    orchestratorConnection: 'Uipath'
    packagesPath: '$(Build.ArtifactStagingDirectory)/Output/'
    folderName: 'Variant_Matrix_Automations'

- script: |
   del /S "$(Build.ArtifactStagingDirectory)\Output\*.nupkg"
  displayName: 'Delete output folder'

- task: UiPathPack@4
  inputs:
    versionType: 'AutoVersion'
    projectJsonPath: '$(Build.SourcesDirectory)/VM_PL02_VerifyTabsForProductLineItem/project.json'
    orchestratorConnection: 'Uipath'
    outputPath: '$(Build.ArtifactStagingDirectory)/Output/'
- task: UiPathDeploy@4
  inputs:
    orchestratorConnection: 'Uipath'
    packagesPath: '$(Build.ArtifactStagingDirectory)/Output/'
    folderName: 'Variant_Matrix_Automations'

- script: |
   del /S "$(Build.ArtifactStagingDirectory)\Output\*.nupkg"
  displayName: 'Delete output folder'

- task: UiPathPack@4
  inputs:
    versionType: 'AutoVersion'
    projectJsonPath: '$(Build.SourcesDirectory)/VM_PL03_VerifyUIComponentsOfVMTab/project.json'
    orchestratorConnection: 'Uipath'
    outputPath: '$(Build.ArtifactStagingDirectory)/Output/'
- task: UiPathDeploy@4
  inputs:
    orchestratorConnection: 'Uipath'
    packagesPath: '$(Build.ArtifactStagingDirectory)/Output/'
    folderName: 'Variant_Matrix_Automations'

- script: |
   del /S "$(Build.ArtifactStagingDirectory)\Output\*.nupkg"
  displayName: 'Delete output folder'

- task: UiPathPack@4
  inputs:
    versionType: 'AutoVersion'
    projectJsonPath: '$(Build.SourcesDirectory)/VM_PL04_VerifyCommandPositioningOnVMTab/project.json'
    orchestratorConnection: 'Uipath'
    outputPath: '$(Build.ArtifactStagingDirectory)/Output/'
- task: UiPathDeploy@4
  inputs:
    orchestratorConnection: 'Uipath'
    packagesPath: '$(Build.ArtifactStagingDirectory)/Output/'
    folderName: 'Variant_Matrix_Automations'

- script: |
   del /S "$(Build.ArtifactStagingDirectory)\Output\*.nupkg"
  displayName: 'Delete output folder'

- task: UiPathPack@4
  inputs:
    versionType: 'AutoVersion'
    projectJsonPath: '$(Build.SourcesDirectory)/VM_PL05_PositionOfVariantMatrixTabOnUI/project.json'
    orchestratorConnection: 'Uipath'
    outputPath: '$(Build.ArtifactStagingDirectory)/Output/'
- task: UiPathDeploy@4
  inputs:
    orchestratorConnection: 'Uipath'
    packagesPath: '$(Build.ArtifactStagingDirectory)/Output/'
    folderName: 'Variant_Matrix_Automations'

- script: |
   del /S "$(Build.ArtifactStagingDirectory)\Output\*.nupkg"
  displayName: 'Delete output folder'

- task: UiPathPack@4
  inputs:
    versionType: 'AutoVersion'
    projectJsonPath: '$(Build.SourcesDirectory)/VM_PL09_PositionOfFullScreenButtonOnUI/project.json'
    orchestratorConnection: 'Uipath'
    outputPath: '$(Build.ArtifactStagingDirectory)/Output/'
- task: UiPathDeploy@4
  inputs:
    orchestratorConnection: 'Uipath'
    packagesPath: '$(Build.ArtifactStagingDirectory)/Output/'
    folderName: 'Variant_Matrix_Automations'

- script: |
   del /S "$(Build.ArtifactStagingDirectory)\Output\*.nupkg"
  displayName: 'Delete output folder'

- task: UiPathPack@4
  inputs:
    versionType: 'AutoVersion'
    projectJsonPath: '$(Build.SourcesDirectory)/VM_Module01_AddNewModuleORProductLineToTheProductLine/project.json'
    orchestratorConnection: 'Uipath'
    outputPath: '$(Build.ArtifactStagingDirectory)/Output/'
- task: UiPathDeploy@4
  inputs:
    orchestratorConnection: 'Uipath'
    packagesPath: '$(Build.ArtifactStagingDirectory)/Output/'
    folderName: 'Variant_Matrix_Automations'

- script: |
   del /S "$(Build.ArtifactStagingDirectory)\Output\*.nupkg"
  displayName: 'Delete output folder'

- task: UiPathPack@4
  inputs:
    versionType: 'AutoVersion'
    projectJsonPath: '$(Build.SourcesDirectory)/VM_Module02_AddExistingModuleORProductLinetoTheProductLine/project.json'
    orchestratorConnection: 'Uipath'
    outputPath: '$(Build.ArtifactStagingDirectory)/Output/'
- task: UiPathDeploy@4
  inputs:
    orchestratorConnection: 'Uipath'
    packagesPath: '$(Build.ArtifactStagingDirectory)/Output/'
    folderName: 'Variant_Matrix_Automations'

- script: |
   del /S "$(Build.ArtifactStagingDirectory)\Output\*.nupkg"
  displayName: 'Delete output folder'

- task: UiPathPack@4
  inputs:
    versionType: 'AutoVersion'
    projectJsonPath: '$(Build.SourcesDirectory)/VM_Module03_AddVariantsofModuleORPLtoParentProductLine/project.json'
    orchestratorConnection: 'Uipath'
    outputPath: '$(Build.ArtifactStagingDirectory)/Output/'
- task: UiPathDeploy@4
  inputs:
    orchestratorConnection: 'Uipath'
    packagesPath: '$(Build.ArtifactStagingDirectory)/Output/'
    folderName: 'Variant_Matrix_Automations'

- script: |
   del /S "$(Build.ArtifactStagingDirectory)\Output\*.nupkg"
  displayName: 'Delete output folder'

- task: UiPathPack@4
  inputs:
    versionType: 'AutoVersion'
    projectJsonPath: '$(Build.SourcesDirectory)/VM_Substitute_01_AssignSubstituteBOMItemsforSelectedVariantBOMItemPaletteTab/project.json'
    orchestratorConnection: 'Uipath'
    outputPath: '$(Build.ArtifactStagingDirectory)/Output/'
- task: UiPathDeploy@4
  inputs:
    orchestratorConnection: 'Uipath'
    packagesPath: '$(Build.ArtifactStagingDirectory)/Output/'
    folderName: 'Variant_Matrix_Automations'

- script: |
   del /S "$(Build.ArtifactStagingDirectory)\Output\*.nupkg"
  displayName: 'Delete output folder'

- task: UiPathPack@4
  inputs:
    versionType: 'AutoVersion'
    projectJsonPath: '$(Build.SourcesDirectory)/VM_Substitute_01_AssignSubstituteBOMItemsForSelectedVariantBOMItemSearchTab/project.json'
    orchestratorConnection: 'Uipath'
    outputPath: '$(Build.ArtifactStagingDirectory)/Output/'
- task: UiPathDeploy@4
  inputs:
    orchestratorConnection: 'Uipath'
    packagesPath: '$(Build.ArtifactStagingDirectory)/Output/'
    folderName: 'Variant_Matrix_Automations'

- script: |
   del /S "$(Build.ArtifactStagingDirectory)\Output\*.nupkg"
  displayName: 'Delete output folder'

- task: UiPathPack@4
  inputs:
    versionType: 'AutoVersion'
    projectJsonPath: '$(Build.SourcesDirectory)/VM_Substitute_02_ShowSubstituteForSelectedBOMItems/project.json'
    orchestratorConnection: 'Uipath'
    outputPath: '$(Build.ArtifactStagingDirectory)/Output/'
- task: UiPathDeploy@4
  inputs:
    orchestratorConnection: 'Uipath'
    packagesPath: '$(Build.ArtifactStagingDirectory)/Output/'
    folderName: 'Variant_Matrix_Automations'

- script: |
   del /S "$(Build.ArtifactStagingDirectory)\Output\*.nupkg"
  displayName: 'Delete output folder'

- task: UiPathPack@4
  inputs:
    versionType: 'AutoVersion'
    projectJsonPath: '$(Build.SourcesDirectory)/VM_Substitute_03_RemoveSubstituteBOMItemsForASelectedVariantBOMItem/project.json'
    orchestratorConnection: 'Uipath'
    outputPath: '$(Build.ArtifactStagingDirectory)/Output/'
- task: UiPathDeploy@4
  inputs:
    orchestratorConnection: 'Uipath'
    packagesPath: '$(Build.ArtifactStagingDirectory)/Output/'
    folderName: 'Variant_Matrix_Automations'

- script: |
   del /S "$(Build.ArtifactStagingDirectory)\Output\*.nupkg"
  displayName: 'Delete output folder'

- task: UiPathPack@4
  inputs:
    versionType: 'AutoVersion'
    projectJsonPath: '$(Build.SourcesDirectory)/VM_Substitute_04_Show BOMItemSubstitutesForSelectedParts/project.json'
    orchestratorConnection: 'Uipath'
    outputPath: '$(Build.ArtifactStagingDirectory)/Output/'
- task: UiPathDeploy@4
  inputs:
    orchestratorConnection: 'Uipath'
    packagesPath: '$(Build.ArtifactStagingDirectory)/Output/'
    folderName: 'Variant_Matrix_Automations'

- script: |
   del /S "$(Build.ArtifactStagingDirectory)\Output\*.nupkg"
  displayName: 'Delete output folder'

- task: UiPathPack@4
  inputs:
    versionType: 'AutoVersion'
    projectJsonPath: '$(Build.SourcesDirectory)/VM_Substitute_05_ShowAllSubstituteBOMItemsForPLItem/project.json'
    orchestratorConnection: 'Uipath'
    outputPath: '$(Build.ArtifactStagingDirectory)/Output/'
- task: UiPathDeploy@4
  inputs:
    orchestratorConnection: 'Uipath'
    packagesPath: '$(Build.ArtifactStagingDirectory)/Output/'
    folderName: 'Variant_Matrix_Automations'

- script: |
   del /S "$(Build.ArtifactStagingDirectory)\Output\*.nupkg"
  displayName: 'Delete output folder'

- task: UiPathPack@4
  inputs:
    versionType: 'AutoVersion'
    projectJsonPath: '$(Build.SourcesDirectory)/VM_Substitute_06_AddSubstituteAndShowItOnPL/project.json'
    orchestratorConnection: 'Uipath'
    outputPath: '$(Build.ArtifactStagingDirectory)/Output/'
- task: UiPathDeploy@4
  inputs:
    orchestratorConnection: 'Uipath'
    packagesPath: '$(Build.ArtifactStagingDirectory)/Output/'
    folderName: 'Variant_Matrix_Automations'

- script: |
   del /S "$(Build.ArtifactStagingDirectory)\Output\*.nupkg"
  displayName: 'Delete output folder'

- task: UiPathPack@4
  inputs:
    versionType: 'AutoVersion'
    projectJsonPath: '$(Build.SourcesDirectory)/VM_ColumnOpertaions01_SaveAsOpertaionOnSourceVariant/project.json'
    orchestratorConnection: 'Uipath'
    outputPath: '$(Build.ArtifactStagingDirectory)/Output/'
- task: UiPathDeploy@4
  inputs:
    orchestratorConnection: 'Uipath'
    packagesPath: '$(Build.ArtifactStagingDirectory)/Output/'
    folderName: 'Variant_Matrix_Automations'

- script: |
   del /S "$(Build.ArtifactStagingDirectory)\Output\*.nupkg"
  displayName: 'Delete output folder'

- task: UiPathPack@4
  inputs:
    versionType: 'AutoVersion'
    projectJsonPath: '$(Build.SourcesDirectory)/VM_ColumnOpertaions02_SelectVariantInMatrixtable/project.json'
    orchestratorConnection: 'Uipath'
    outputPath: '$(Build.ArtifactStagingDirectory)/Output/'
- task: UiPathDeploy@4
  inputs:
    orchestratorConnection: 'Uipath'
    packagesPath: '$(Build.ArtifactStagingDirectory)/Output/'
    folderName: 'Variant_Matrix_Automations'

- script: |
   del /S "$(Build.ArtifactStagingDirectory)\Output\*.nupkg"
  displayName: 'Delete output folder'

- task: UiPathPack@4
  inputs:
    versionType: 'AutoVersion'
    projectJsonPath: '$(Build.SourcesDirectory)/VM_ColumnOpertaions03_OpenVariantFromMatrixTable/project.json'
    orchestratorConnection: 'Uipath'
    outputPath: '$(Build.ArtifactStagingDirectory)/Output/'
- task: UiPathDeploy@4
  inputs:
    orchestratorConnection: 'Uipath'
    packagesPath: '$(Build.ArtifactStagingDirectory)/Output/'
    folderName: 'Variant_Matrix_Automations'

- script: |
   del /S "$(Build.ArtifactStagingDirectory)\Output\*.nupkg"
  displayName: 'Delete output folder'

