
trigger:
- main
 
pool:
  uipath
 
steps:
 
- task: UiPathPack@4
  inputs:
    versionType: 'AutoVersion'
    projectJsonPath: '$(Build.SourcesDirectory)/VM_ColumnOpertaions01_SaveAsOpertaionOnSourceVariant/project.json'
    orchestratorConnection: 'Uipath'
    outputPath: '$(Build.ArtifactStagingDirectory)/Output/'
- task: UiPathDeploy@4
  inputs:
    orchestratorConnection: 'Uipath'
    packagesPath: '$(Build.ArtifactStagingDirectory)/Output/'
    folderName: 'Variant_Matrix_Automations'

- script: |
   del /S "$(Build.ArtifactStagingDirectory)\Output\*.nupkg"
  displayName: 'Create Required output folder'