

variables:
  orchestratorConnection: 'Uipath'
  folderName: 'Variant_Matrix_Automations'

parameters:
  - name: testSet
    displayName: Test Set Name
    type: string
    default: 'VariantMatrix02'
    values:
      - VariantMatrix01
      - VariantMatrix02

pool:
  uipath

steps:
- task: UiPathTest@4
  inputs:
    testTarget: 'TestSet'
    orchestratorConnection: $(orchestratorConnection)
    testSet: ${{ parameters.testSet }}
    folderName: $(folderName)
